### ISSUE TITLE
chifra cmd - articulation: ABIs download and cache APIs

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2523]
The very first step to port `--articulate` to Go would be to build APIs for downloading and caching ABI files. 
What we need to take into consideration is that we will be dealing with multiple sources providing the files: HTTP services and IPFS nodes. 

### Predefined ABI sources
We should have at least 2 ABI sources predefined: Sourcify and Etherscan.

**Sourcify**
By default, we fetch ABIs from Sourcify using local IPFS node (starting one if it's not running), with **sharing** turned on. The user can override these settings, e.g. turning sharing off or deciding to use a gateway (via HTTP) instead of IPFS node (this is what Brave allows for users that are low on system resources: https://brave.com/ipfs-support/)

```toml
[abis]
# IPFS transport and sharing by default
provider = "sourcify"
```

```toml
[abis]
# HTTP transport (IPFS node is NOT started) and no sharing
provider = "sourcify"
transport = "http"
share = false
```

**Etherscan**
This one can only use HTTP requests to fetch ABIs

```toml
[keys]
[keys.etherscan]
apiKey = "xxxxx"

[abis]
# HTTP transport, no sharing
provider = "etherscan"
```

`share` is silently ignored when using HTTP as `transport` (and when using Etherscan)

### User defined ABI sources
It seems pretty easy add support for user defined ABI sources. User could add URL in form of **Go template** to the configuration file (trueBlocks.toml). If the URL starts with `ipfs://` or `ipns://`, we would try IPFS fetch, if it starts with `https://` or `http://`, then we fetch via HTTP. Any other protocol is unsupported and yields an error. Example configuration:
```toml
[abis]
# instead of "sourcify" or "etherscan", the user sets custom service name here
provider = "myService"

# now the user has to define the service
[abis.providers.myService]
# `contractAddress` will be replaced by the address of the contract
url = "http://example.com/abis/{{contractAddress}}"
```

### Caching

**HTTP transport**
When fetching ABIs via HTTP, the cache works just like in C++ code.

**IPFS**
The major issue with caching in this case is that we do not want to duplicate data, storing ABI files both in the node and our cache. 
This is why we should keep record of what ABIs stored in the node. In the simplest form, it could be done by placing a file with well-known name, for example `cid.ipfs` in our cache, instead of the actual ABI file.

_Cons_:
- we need to open a file first and only then we can call IPFS node. But this can be optimized (by using a single file instead of many to keep track of ABIs stored in IPFS node or by using background server, like for names)

_Pros_:
- no data duplication
- sharing works out of the box (the data is in IPFS node)
- works nicely with C++ code style cache
