### ISSUE TITLE
chifra scrape - Instable node connection 

### ISSUE THREAD

**Issue by tnet-ag** [TrueBlocks/trueblocks-core#3179]
For example when I run **chifra scrape**

It works a while then I get

`

Could not connect to RPC client Post "http://erigon.dappnode:8545": dial tcp ***: connect: cannot assign requested address

`
Then after a while it works again and so on

Could be that client or server run out of free ports?

Running against a erigon which runs on dappnode

**Comment by tnet-ag** [comment]
Happens when directly installed on the machine and when running in docker with docker compose up.

**Comment by tnet-ag** [comment]
Already rebooted dappnode and the server where trueblocks run

Also restarted the erigon container on dappnode

**Comment by dszlachta** [comment]
It seems that this error comes directly from your operating system... Can you paste the command that you use to run TrueBlocks docker container?

**Comment by tnet-ag** [comment]
its docker compose up

with the following docker-compose.yml 

```
# UPDATE_DOCKER_BUILD_VERSION
services:
  core:
    image: trueblocks/core:v0.70.0-beta
    build: ./
    env_file: .env
    ports:
      - "8080:${SERVE_PORT-8080}"
    volumes:
      - type: bind
        # The source should match the folder you made to store the cache
        source: ****/cache
        target: /cache
      - type: bind
        # The source should match the folder you made to store the Unchained index
        source: ****/unchained
        target: /unchained

    network_mode: "host"
volumes:
  unchained:
  cache:
```
